### ISSUE TITLE
Test and document current chart usage on AWS

### ISSUE THREAD

**Issue by voidmarcus** [A3Data/pyspark-notebook-helm#1]

**Comment by neylsoncrepalde** [comment]
Hey guys. I tried To deploy the chart on AWS. Couldn't do it.

First, when I try to update dependencies, I get this error:

```bash
helm dependency update Chart.yaml 
```
```
Error: only unpacked charts can be updated
```

Then, after installing the chart, statefulset and pod get stuck on _pending_.

```bash
kubectl create namespace notebook
helm install pyspark . -n notebook
kubectl get all -n notebook
```

```
NAME            READY   STATUS    RESTARTS   AGE
pod/pyspark-0   0/1     Pending   0          5m16s

NAME                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
service/pyspark            ClusterIP   10.100.99.60   <none>        8888/TCP,7777/TCP,2222/TCP   5m18s
service/pyspark-headless   ClusterIP   None           <none>        8888/TCP,7777/TCP,2222/TCP   5m18s

NAME                       READY   AGE
statefulset.apps/pyspark   0/1     5m20s
```

I have a K8s cluster running on top of two m5.xlarge spot instances. At the test moment, nodes were available.

**Comment by neylsoncrepalde** [comment]
Also tried to deploy a k8s secret with aws credentials. Didn't help...

```yaml
# Allows you to load environment variables from kubernetes secret               
secret:                                                                         
  - envName: AWS_ACCESS_KEY_ID                                                  
    secretName: aws-credentials                                                 
    secretKey: aws_access_key_id                                                
  - envName: AWS_SECRET_ACCESS_KEY                                              
    secretName: aws-credentials                                                 
    secretKey: aws_secret_access_key          
```
